name: generate doxygen documentation
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                ref: main
            - name: Install Doxygen
              run: |
                   wget https://www.doxygen.nl/files/doxygen-1.13.2.linux.bin.tar.gz
                   tar -xvzf doxygen-1.13.2.linux.bin.tar.gz
                   mkdir doxygen
                   sudo cp doxygen-1.13.2/bin/doxygen doxygen
                   export PATH=$PATH:doxygen
                   source ~/.bashrc
                   sudo apt install graphviz -y
                   git submodule add https://github.com/jothepro/doxygen-awesome-css.git

            - name: Generate Doxygen documentation
              run: |
                  ls -la
                  ./doxygen/doxygen Doxyfile

            - name: Deploy Doxygen documentation
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.DOCS_TOKEN }}
                  publish_dir: ./docs/html